/* Copyright (C) 1999 Masanao Izumo <iz@onicos.co.jp>
 * Version: 1.0
 * LastModified: Dec 25 1999
 * This library is free.  You can redistribute it and/or modify it.
 */

/*
 * Interfaces:
 * b64 = base64encode(data);
 * data = base64decode(b64);
 */

(function(){function n(t){var n,r,i;var s,o,u;i=t.length;r=0;n="";while(r<i){s=t.charCodeAt(r++)&255;if(r==i){n+=e.charAt(s>>2);n+=e.charAt((s&3)<<4);n+="==";break}o=t.charCodeAt(r++);if(r==i){n+=e.charAt(s>>2);n+=e.charAt((s&3)<<4|(o&240)>>4);n+=e.charAt((o&15)<<2);n+="=";break}u=t.charCodeAt(r++);n+=e.charAt(s>>2);n+=e.charAt((s&3)<<4|(o&240)>>4);n+=e.charAt((o&15)<<2|(u&192)>>6);n+=e.charAt(u&63)}return n}function r(e){var n,r,i,s;var o,u,a;u=e.length;o=0;a="";while(o<u){do{n=t[e.charCodeAt(o++)&255]}while(o<u&&n==-1);if(n==-1)break;do{r=t[e.charCodeAt(o++)&255]}while(o<u&&r==-1);if(r==-1)break;a+=String.fromCharCode(n<<2|(r&48)>>4);do{i=e.charCodeAt(o++)&255;if(i==61)return a;i=t[i]}while(o<u&&i==-1);if(i==-1)break;a+=String.fromCharCode((r&15)<<4|(i&60)>>2);do{s=e.charCodeAt(o++)&255;if(s==61)return a;s=t[s]}while(o<u&&s==-1);if(s==-1)break;a+=String.fromCharCode((i&3)<<6|s)}return a}var e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var t=new Array(-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1);if(!window.btoa)window.btoa=n;if(!window.atob)window.atob=r})()

/*
 * Canvas2Image v0.1
 * Copyright (c) 2008 Jacob Seidelin, jseidelin@nihilogic.dk
 * MIT License [http://www.opensource.org/licenses/mit-license.php]
 */

var Canvas2Image=function(){var e=false;var t=document.createElement("canvas");if(t.getContext("2d")){e=true}if(!e){return{saveAsBMP:function(){},saveAsPNG:function(){},saveAsJPEG:function(){}}}var n=!!t.getContext("2d").getImageData;var r=!!t.toDataURL;var i=!!window.btoa;var s="image/octet-stream";var o=function(e){var t=parseInt(e.width);var n=parseInt(e.height);return e.getContext("2d").getImageData(0,0,t,n)};var u=function(e){var t="";if(typeof e=="string"){t=e}else{var n=e;for(var r=0;r<n.length;r++){t+=String.fromCharCode(n[r])}}return btoa(t)};var a=function(e){var t=[];var n=e.width;var r=e.height;t.push(66);t.push(77);var i=n*r*3+54;t.push(i%256);i=Math.floor(i/256);t.push(i%256);i=Math.floor(i/256);t.push(i%256);i=Math.floor(i/256);t.push(i%256);t.push(0);t.push(0);t.push(0);t.push(0);t.push(54);t.push(0);t.push(0);t.push(0);var s=[];s.push(40);s.push(0);s.push(0);s.push(0);var o=n;s.push(o%256);o=Math.floor(o/256);s.push(o%256);o=Math.floor(o/256);s.push(o%256);o=Math.floor(o/256);s.push(o%256);var a=r;s.push(a%256);a=Math.floor(a/256);s.push(a%256);a=Math.floor(a/256);s.push(a%256);a=Math.floor(a/256);s.push(a%256);s.push(1);s.push(0);s.push(24);s.push(0);s.push(0);s.push(0);s.push(0);s.push(0);var f=n*r*3;s.push(f%256);f=Math.floor(f/256);s.push(f%256);f=Math.floor(f/256);s.push(f%256);f=Math.floor(f/256);s.push(f%256);for(var l=0;l<16;l++){s.push(0)}var c=(4-n*3%4)%4;var h=e.data;var p="";var d=r;do{var v=n*(d-1)*4;var m="";for(var g=0;g<n;g++){var y=4*g;m+=String.fromCharCode(h[v+y+2]);m+=String.fromCharCode(h[v+y+1]);m+=String.fromCharCode(h[v+y])}for(var b=0;b<c;b++){m+=String.fromCharCode(0)}p+=m}while(--d);var w=u(t.concat(s))+u(p);return w};var f=function(e){document.location.href=e};var l=function(e,t){return"data:"+t+";base64,"+e};var c=function(e){var t=document.createElement("img");t.src=e;return t};var h=function(e,t,n){if(t&&n){var r=document.createElement("canvas");r.width=t;r.height=n;r.style.width=t+"px";r.style.height=n+"px";var i=r.getContext("2d");i.drawImage(e,0,0,e.width,e.height,0,0,t,n);return r}return e};return{saveAsPNG:function(e,t,n,i){if(!r){return false}var o=h(e,n,i);var u=o.toDataURL("image/png");if(t){return c(u)}else{f(u.replace("image/png",s))}return true},saveAsJPEG:function(e,t,n,i){if(!r){return false}var o=h(e,n,i);var u="image/jpeg";var a=o.toDataURL(u);if(a.indexOf(u)!=5){return false}if(t){return c(a)}else{f(a.replace(u,s))}return true},saveAsBMP:function(e,t,r,u){if(!(n&&i)){return false}var p=h(e,r,u);var d=o(p);var v=a(d);if(t){return c(l(v,"image/bmp"))}else{f(l(v,s))}return true}}}()